FROM python:3

WORKDIR /jule-backend

ENV FLASK_APP=app:create_app

ENV FLASK_ENV=development

COPY ./jule-backend/requirements.txt .

RUN pip install -r requirements.txt

CMD ["python", "-m", "flask", "run", "--host", "0.0.0.0"]
